# Generated by Django 5.2.17 on 2026-09-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_stripewebhookevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderSlot",
            fields=[
                (
                    "sequence",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("checkout_expires_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="founder_slot",
                        to="billing.billingcustomer",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1), ("sequence__lte", 20)),
                        name="billing_founder_slot_sequence_1_20",
                    )
                ],
            },
        ),
    ]
