# Generated by Django 5.2.17 on 2026-09-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_founderslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="founderslot",
            name="reservation_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
